### ISSUE TITLE
Devhub Issue: Open Source Code - Invalid Create An Issue URL

### ISSUE THREAD

**Issue by cvarjao** [bcgov/devhub-resources#18]
> path: (do not delete) https://github.com/bcgov/devhub-resources/blob/master/resources/alignment/opensource.md
 > (do not delete) devhub page: Open-Source-Code

## Devhub Content Issue
The `Create An Issue` link is pointing to an invalid URL. There seem to be an `undefined` value concatenated with `bcgov`, producing `undefinedbcgov`.
```
https://www.github.com/undefinedbcgov/devhub-resources/issues/new?title=Devhub%20Issue%3A%20Open%20Source%20Code%20%5Bshort%20description%20here%5D&body=%3E%20path%3A%20(do%20not%20delete)%20https%3A%2F%2Fgithub.com%2Fbcgov%2Fdevhub-resources%2Fblob%2Fmaster%2Fresources%2Falignment%2Fopensource.md%0A%20%3E%20(do%20not%20delete)%20devhub%20page%3A%20Open-Source-Code%0A%0A%23%23%20Devhub%20Content%20Issue%0A
```

**Comment by patricksimonian** [comment]
I am unable to replicate this issue :S

**Comment by patricksimonian** [comment]
this issue has been resolved with https://github.com/bcgov/devhub-app-web/pull/1035 :)
