### ISSUE TITLE
Devhub Issue: Communication, Community and Support - slack change

### ISSUE THREAD

**Issue by kelpisland** [bcgov/devhub-resources#3]
> path: (do not delete) https://github.com/bcgov/devhub-resources/blob/master/resources/alignment/communication_community_and_support.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/Communication-Community-and-Support

## Devhub Content Issue
text refers to Slack - update to Rocket

**Comment by sheaphillips** [comment]
Fixed content.
