### ISSUE TITLE
Devhub Issue: Chat Channel Conventions add following channel

### ISSUE THREAD

**Issue by ll911** [bcgov/devhub-resources#4]
> path: (do not delete) https://github.com/bcgov/devhub-resources/blob/master/resources/community/chat_conventions.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Community-Enablers-and-Events/Chat-Channel-Conventions

## Devhub Content Issue
https://chat.pathfinder.gov.bc.ca/channel/geows-how-to

Geo Spatial Web Services How-to, this is the channel you can inquiry how to consume Province provided spatial webservices such as WMS, WFS, ArcGIS REST services with your web applications.

**Comment by patricksimonian** [comment]
Thanks for the issue. We've taken note of it and will organize it into our workflow. As an aside we are happy to accept any PR's for documentation issues :)

**Comment by ll911** [comment]
https://github.com/bcgov/devhub-resources/pull/6
